name: Check branch name format

on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  check_branch_name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name matches pattern
        run: |
          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "Current branch: $BRANCH_NAME"

          if [[ ! "$BRANCH_NAME" =~ ^[0-9]+[-_][a-zA-Z0-9_äöõüÄÖÕÜ-]+$ ]]; then
            echo "❌ Haru nimi peab olema kujul: number_snake_or_kebab_case_nimi"
            echo "Näide: 42-edit-assignment-criteria või 42_edit_assignment_criteria või 16_learning_outcomes_õv"
            exit 1
          fi
